# Site settings
baseurl = "http://callme.ninja/"
languageCode = "en-us"
title = "Ninja Dude"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "callmeninja"

[params]
	name = "Shuaib Yunus"
	description = "."
	bio = "Tamperer - Dude"
	# Enter optionally your twitter account
	twitter = "shuaibiyy"
	enableRSS = false

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Me. We."
	tweet = "@shuaibiyy"
	share = ""
	# 404 page
	title404 = "I don't know what to tell ya!"
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/shuaibiyy"
    github   = "https://www.github.com/shuaibiyy"
