baseurl = "http://callme.ninja/"
languageCode = "en-us"
title = "Call Me Ninja"
theme = "hugo-hikari-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Call Me Ninja"
	description = "Stuff as I see it."
	copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © Shuaib Yunus"

	# Enable comments by entering your Disqus shortname
	disqusshortname = "shuaibiyy"
	# Enable Google Analytics by entering your tracking code
	googleanalytics = ""

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Shuaib"
	bio = "Impostor and Tinkerer"
	subscribe = "Subscribe"
	followme = "Follow me on"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/shuaibiyy"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/shuaibiyy"